const COUNTRIES = [
  { country: "United States", capital: "Washington, D.C.", continent: "North America", code: "USA", flag: "🇺🇸", lat: 39.8, lng: -98.6, level: "easy" },
  { country: "Canada", capital: "Ottawa", continent: "North America", code: "CAN", flag: "🇨🇦", lat: 56.1, lng: -106.3, level: "easy" },
  { country: "Mexico", capital: "Mexico City", continent: "North America", code: "MEX", flag: "🇲🇽", lat: 23.6, lng: -102.5, level: "easy" },
  { country: "Brazil", capital: "Brasília", continent: "South America", code: "BRA", flag: "🇧🇷", lat: -14.2, lng: -51.9, level: "easy" },
  { country: "United Kingdom", capital: "London", continent: "Europe", code: "GBR", flag: "🇬🇧", lat: 55.4, lng: -3.4, level: "easy" },
  { country: "France", capital: "Paris", continent: "Europe", code: "FRA", flag: "🇫🇷", lat: 46.2, lng: 2.2, level: "easy" },
  { country: "Germany", capital: "Berlin", continent: "Europe", code: "DEU", flag: "🇩🇪", lat: 51.2, lng: 10.4, level: "easy" },
  { country: "Italy", capital: "Rome", continent: "Europe", code: "ITA", flag: "🇮🇹", lat: 41.9, lng: 12.6, level: "easy" },
  { country: "India", capital: "New Delhi", continent: "Asia", code: "IND", flag: "🇮🇳", lat: 20.6, lng: 79.0, level: "easy" },
  { country: "Japan", capital: "Tokyo", continent: "Asia", code: "JPN", flag: "🇯🇵", lat: 36.2, lng: 138.3, level: "easy" },
  { country: "China", capital: "Beijing", continent: "Asia", code: "CHN", flag: "🇨🇳", lat: 35.9, lng: 104.2, level: "easy" },
  { country: "Australia", capital: "Canberra", continent: "Oceania", code: "AUS", flag: "🇦🇺", lat: -25.3, lng: 133.8, level: "easy" },
  { country: "Egypt", capital: "Cairo", continent: "Africa", code: "EGY", flag: "🇪🇬", lat: 26.8, lng: 30.8, level: "easy" },
  { country: "South Africa", capital: "Pretoria", continent: "Africa", code: "ZAF", flag: "🇿🇦", lat: -30.6, lng: 22.9, level: "easy" },
  { country: "Spain", capital: "Madrid", continent: "Europe", code: "ESP", flag: "🇪🇸", lat: 40.5, lng: -3.7, level: "easy" },

  { country: "Argentina", capital: "Buenos Aires", continent: "South America", code: "ARG", flag: "🇦🇷", lat: -38.4, lng: -63.6, level: "medium" },
  { country: "Chile", capital: "Santiago", continent: "South America", code: "CHL", flag: "🇨🇱", lat: -35.7, lng: -71.5, level: "medium" },
  { country: "Peru", capital: "Lima", continent: "South America", code: "PER", flag: "🇵🇪", lat: -9.2, lng: -75.0, level: "medium" },
  { country: "Portugal", capital: "Lisbon", continent: "Europe", code: "PRT", flag: "🇵🇹", lat: 39.4, lng: -8.2, level: "medium" },
  { country: "Greece", capital: "Athens", continent: "Europe", code: "GRC", flag: "🇬🇷", lat: 39.1, lng: 21.8, level: "medium" },
  { country: "Norway", capital: "Oslo", continent: "Europe", code: "NOR", flag: "🇳🇴", lat: 60.5, lng: 8.5, level: "medium" },
  { country: "Sweden", capital: "Stockholm", continent: "Europe", code: "SWE", flag: "🇸🇪", lat: 60.1, lng: 18.6, level: "medium" },
  { country: "Finland", capital: "Helsinki", continent: "Europe", code: "FIN", flag: "🇫🇮", lat: 61.9, lng: 25.7, level: "medium" },
  { country: "Poland", capital: "Warsaw", continent: "Europe", code: "POL", flag: "🇵🇱", lat: 51.9, lng: 19.1, level: "medium" },
  { country: "Turkey", capital: "Ankara", continent: "Asia", code: "TUR", flag: "🇹🇷", lat: 39.0, lng: 35.2, level: "medium" },
  { country: "Saudi Arabia", capital: "Riyadh", continent: "Asia", code: "SAU", flag: "🇸🇦", lat: 23.9, lng: 45.1, level: "medium" },
  { country: "Thailand", capital: "Bangkok", continent: "Asia", code: "THA", flag: "🇹🇭", lat: 15.9, lng: 100.9, level: "medium" },
  { country: "Vietnam", capital: "Hanoi", continent: "Asia", code: "VNM", flag: "🇻🇳", lat: 14.1, lng: 108.3, level: "medium" },
  { country: "South Korea", capital: "Seoul", continent: "Asia", code: "KOR", flag: "🇰🇷", lat: 35.9, lng: 127.8, level: "medium" },
  { country: "New Zealand", capital: "Wellington", continent: "Oceania", code: "NZL", flag: "🇳🇿", lat: -40.9, lng: 174.9, level: "medium" },
  { country: "Nigeria", capital: "Abuja", continent: "Africa", code: "NGA", flag: "🇳🇬", lat: 9.1, lng: 8.7, level: "medium" },

  { country: "Kazakhstan", capital: "Astana", continent: "Asia", code: "KAZ", flag: "🇰🇿", lat: 48.0, lng: 66.9, level: "hard" },
  { country: "Mongolia", capital: "Ulaanbaatar", continent: "Asia", code: "MNG", flag: "🇲🇳", lat: 46.9, lng: 103.8, level: "hard" },
  { country: "Nepal", capital: "Kathmandu", continent: "Asia", code: "NPL", flag: "🇳🇵", lat: 28.4, lng: 84.1, level: "hard" },
  { country: "Bhutan", capital: "Thimphu", continent: "Asia", code: "BTN", flag: "🇧🇹", lat: 27.5, lng: 90.4, level: "hard" },
  { country: "Cambodia", capital: "Phnom Penh", continent: "Asia", code: "KHM", flag: "🇰🇭", lat: 12.6, lng: 105.0, level: "hard" },
  { country: "Laos", capital: "Vientiane", continent: "Asia", code: "LAO", flag: "🇱🇦", lat: 19.9, lng: 102.5, level: "hard" },
  { country: "Ethiopia", capital: "Addis Ababa", continent: "Africa", code: "ETH", flag: "🇪🇹", lat: 9.1, lng: 40.5, level: "hard" },
  { country: "Kenya", capital: "Nairobi", continent: "Africa", code: "KEN", flag: "🇰🇪", lat: -0.0, lng: 37.9, level: "hard" },
  { country: "Morocco", capital: "Rabat", continent: "Africa", code: "MAR", flag: "🇲🇦", lat: 31.8, lng: -7.1, level: "hard" },
  { country: "Tanzania", capital: "Dodoma", continent: "Africa", code: "TZA", flag: "🇹🇿", lat: -6.4, lng: 34.9, level: "hard" },
  { country: "Iceland", capital: "Reykjavík", continent: "Europe", code: "ISL", flag: "🇮🇸", lat: 65.0, lng: -19.0, level: "hard" },
  { country: "Hungary", capital: "Budapest", continent: "Europe", code: "HUN", flag: "🇭🇺", lat: 47.2, lng: 19.5, level: "hard" },
  { country: "Romania", capital: "Bucharest", continent: "Europe", code: "ROU", flag: "🇷🇴", lat: 45.9, lng: 24.9, level: "hard" },
  { country: "Croatia", capital: "Zagreb", continent: "Europe", code: "HRV", flag: "🇭🇷", lat: 45.1, lng: 15.2, level: "hard" },
  { country: "Uruguay", capital: "Montevideo", continent: "South America", code: "URY", flag: "🇺🇾", lat: -32.5, lng: -55.8, level: "hard" }
];
